// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertFolder(arg1, arg2) {
  return window['go']['main']['App']['ConvertFolder'](arg1, arg2);
}

export function ConvertMarkdown(arg1, arg2) {
  return window['go']['main']['App']['ConvertMarkdown'](arg1, arg2);
}

export function SavePDF() {
  return window['go']['main']['App']['SavePDF']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectMarkdownFile() {
  return window['go']['main']['App']['SelectMarkdownFile']();
}
