// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {converter} from '../models';

export function ConvertFolder(arg1:string,arg2:string):Promise<Array<converter.FolderResult>>;

export function ConvertMarkdown(arg1:string,arg2:string):Promise<string>;

export function SavePDF():Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectMarkdownFile():Promise<string>;
